// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"components/accordion.mdx": () => import("../content/docs/components/accordion.mdx?collection=docs"), "components/alert-dialog.mdx": () => import("../content/docs/components/alert-dialog.mdx?collection=docs"), "components/avatar.mdx": () => import("../content/docs/components/avatar.mdx?collection=docs"), "components/button.mdx": () => import("../content/docs/components/button.mdx?collection=docs"), "components/checkbox-group.mdx": () => import("../content/docs/components/checkbox-group.mdx?collection=docs"), "components/checkbox.mdx": () => import("../content/docs/components/checkbox.mdx?collection=docs"), "components/collapsible.mdx": () => import("../content/docs/components/collapsible.mdx?collection=docs"), "components/dialog.mdx": () => import("../content/docs/components/dialog.mdx?collection=docs"), "components/input.mdx": () => import("../content/docs/components/input.mdx?collection=docs"), "components/label.mdx": () => import("../content/docs/components/label.mdx?collection=docs"), "components/popover.mdx": () => import("../content/docs/components/popover.mdx?collection=docs"), "components/progress.mdx": () => import("../content/docs/components/progress.mdx?collection=docs"), "components/radio.mdx": () => import("../content/docs/components/radio.mdx?collection=docs"), "components/separator.mdx": () => import("../content/docs/components/separator.mdx?collection=docs"), "components/skeleton.mdx": () => import("../content/docs/components/skeleton.mdx?collection=docs"), "components/slider.mdx": () => import("../content/docs/components/slider.mdx?collection=docs"), "components/switch.mdx": () => import("../content/docs/components/switch.mdx?collection=docs"), "components/tabs.mdx": () => import("../content/docs/components/tabs.mdx?collection=docs"), "components/toggle-group.mdx": () => import("../content/docs/components/toggle-group.mdx?collection=docs"), "components/toggle.mdx": () => import("../content/docs/components/toggle.mdx?collection=docs"), "components/tooltip.mdx": () => import("../content/docs/components/tooltip.mdx?collection=docs"), }),
};
export default browserCollections;